export const menuData = [
  {
    id: 1000,
    title: 'Лента',
    link: '/',
    icon: require(`@/assets/images/icons/menu/1-default.svg`),
    iconActive: require(`@/assets/images/icons/menu/1-active.svg`),
  },
  {
    id: 1001,
    title: 'Проишествия',
    link: '/proishestvia',
    icon: require(`@/assets/images/icons/menu/2-default.svg`),
    iconActive: require(`@/assets/images/icons/menu/2-active.svg`),
  },
  {
    id: 1002,
    title: 'Авто',
    link: '/avto',
    icon: require(`@/assets/images/icons/menu/3-default.svg`),
    iconActive: require(`@/assets/images/icons/menu/3-active.svg`),
  },
  {
    id: 1003,
    title: 'Бизнес',
    link: '/biznes',
    icon: require(`@/assets/images/icons/menu/4-default.svg`),
    iconActive: require(`@/assets/images/icons/menu/4-active.svg`),
  },
  {
    id: 1004,
    title: 'Здоровье',
    link: '/zdorovje',
    icon: require(`@/assets/images/icons/menu/5-default.svg`),
    iconActive: require(`@/assets/images/icons/menu/5-active.svg`),
  },
  {
    id: 1005,
    title: 'Крипто',
    link: '/kripto',
    icon: require(`@/assets/images/icons/menu/6-default.svg`),
    iconActive: require(`@/assets/images/icons/menu/6-active.svg`),
  },
  {
    id: 1006,
    title: 'Недвижимость',
    link: '/nedvizhmost',
    icon: require(`@/assets/images/icons/menu/7-default.svg`),
    iconActive: require(`@/assets/images/icons/menu/7-active.svg`),
  },
  {
    id: 1007,
    title: 'Образование',
    link: '/obrazovanie',
    icon: require(`@/assets/images/icons/menu/8-default.svg`),
    iconActive: require(`@/assets/images/icons/menu/8-active.svg`),
  },
  {
    id: 1008,
    title: 'Политика',
    link: '/politica',
    icon: require(`@/assets/images/icons/menu/9-default.svg`),
    iconActive: require(`@/assets/images/icons/menu/9-active.svg`),
  },
  {
    id: 1009,
    title: 'Туризм',
    link: '/turizm',
    icon: require(`@/assets/images/icons/menu/10-default.svg`),
    iconActive: require(`@/assets/images/icons/menu/10-active.svg`),
  },
  {
    id: 1010,
    title: 'Шоу-бизнес',
    link: '/shoy-biznes',
    icon: require(`@/assets/images/icons/menu/11-default.svg`),
    iconActive: require(`@/assets/images/icons/menu/11-active.svg`),
  },
  {
    id: 1011,
    title: 'Спорт',
    link: '/sport',
    icon: require(`@/assets/images/icons/menu/12-default.svg`),
    iconActive: require(`@/assets/images/icons/menu/12-active.svg`),
  },
  {
    id: 1012,
    title: 'Стиль',
    link: '/stil',
    icon: require(`@/assets/images/icons/menu/13-default.svg`),
    iconActive: require(`@/assets/images/icons/menu/13-active.svg`),
  },
  {
    id: 1013,
    title: 'Наука и технологии',
    link: '/nayka-i-tekhnologii',
    icon: require(`@/assets/images/icons/menu/14-default.svg`),
    iconActive: require(`@/assets/images/icons/menu/14-active.svg`),
  },
  {
    id: 1014,
    title: 'Экономика',
    link: '/ekonomika',
    icon: require(`@/assets/images/icons/menu/15-default.svg`),
    iconActive: require(`@/assets/images/icons/menu/15-active.svg`),
  },
]
